<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3bb662307b4b5f04f87bb9f9adb8bac5
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPImageWorkshop\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPImageWorkshop\\' => 
        array (
            0 => __DIR__ . '/..' . '/sybio/image-workshop/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3bb662307b4b5f04f87bb9f9adb8bac5::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3bb662307b4b5f04f87bb9f9adb8bac5::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit3bb662307b4b5f04f87bb9f9adb8bac5::$classMap;

        }, null, ClassLoader::class);
    }
}
